name: build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        javaVersion: ['1.8','14']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.javaVersion }}
    - name: "compile"
      run: mvn -B clean install